# environment.yaml

channels:
  - conda-forge
dependencies:
  - python==3.12.8
  - mne==1.9.0
  - numpy==1.26.4
  - pandas==2.2.1
  - PySide6==6.8.1
  - statsmodels>=0.13.1
  - scipy>=1.7.1
  - spectrum>=0.8.0
  - matplotlib==3.8.4
  - ruamel.yaml==0.18.6
  - plotly==5.24.1
  - pip
  - pip:
    - shutils>=0.1.0
    # - -r requirements.txt