name: test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          cache: pip
      
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
              
      - name: Install dependencies
        run: pip install -r requirements.txt
              
      - name: Install pytest
        run: python -m pip install pytest
      
      - name: Run tests
        run: python -m pytest tests/
        
      
